### ISSUE TITLE
运行后·

### ISSUE THREAD

**Issue by HuWeihuaDemo** [ddiu8081/ChartFun#14]
还要登录啊，有密码吗

**Comment by ddiu8081** [comment]
没有默认账户，需要配置好mongodb环境后注册一个。

**Comment by JamsGu** [comment]
连接mongodb数据库成功。but没有自动创建表结构。

**Comment by ddiu8081** [comment]
连接成功的话，一般会在下次操作数据库的时候立即创建，在首页注册账号试一下
