### ISSUE TITLE
依赖下载失败

### ISSUE THREAD

**Issue by KingWang6** [ddiu8081/ChartFun#6]
你好，请问node和npm的版本是多少? 我的node是v10.16.0, npm是v6.9.0，总是下载依赖出现出错。

**Comment by ddiu8081** [comment]
我的环境是node v8.15.1，npm v6.9.0。
可以查看npm install时是哪个依赖出错，如果是cypress，可以从package.json中删除cypress项重试。

**Comment by KingWang6** [comment]
好的，谢谢。
